- hosts: all
  become: true
  become_user: root
  tasks:
      - name: Copy
        copy:
          src: /etc/hosts
          dest: /tmp/test1
          owner: apurva
          group: apurva
          mode: 0777
        when: ansible_distribution == 'RedHat'
