- hosts: aws
  become: true
  become_user: root
  tasks:
     - name:  testing lineinfile
       lineinfile:
         path: /tmp/new1
         regexp: '^SELINUX'
         line: SELINUX=enforcing
     - name: testing2
       lineinfile:
           path: /etc/sudoers
           state: absent
           regexp: '^%wheel'
     - name: Replace a localhost entry with our own
       lineinfile:
          path: /tmp/new1
          regexp: '^127\.0\.0\.1'
          line: 127.0.0.1 localhost
          owner: root
          group: root
          mode: '0644'
